# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Uploader
version:      0.76_02
version_from: lib/CGI/Uploader.pm
installdirs:  site
requires:
    Carp::Assert:                  0
    CGI:                           0
    CGI::Carp:                     0
    DBI:                           0
    Digest::MD5:                   0
    File::Copy:                    0
    File::MMagic:                  1.22
    File::Path:                    0
    File::Spec:                    0
    File::Temp:                    0
    Image::Magick:                 0
    Image::Size:                   0
    MIME::Type:                    0
    MIME::Types:                   0
    Params::Validate:              0
    SQL::Abstract:                 0
    Test::DatabaseRow:             0
    Test::Differences:             0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
